/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AstronautResource = AstronautEntry & {
  id: string;
  createdAt: string;
};

export interface ElevenApi {
  findAstronaut: {
    request: {
      id?: string;
      query?: string;
    };
    response: {
      content: AstronautResource[];
    };
  };
  createAstronaut: {
    request: AstronautEntry;
    response: AstronautResource;
  };
  removeAstronaut: {
    request: {
      id: string;
    };
    response: {};
  };
  updateAstronaut: {
    request: AstronautEntry & {
      id: string;
    };
    response: AstronautResource;
  };
}
export interface AstronautEntry {
  avatar?: string;
  firstName: string;
  lastName: string;
  exp: number;
  job?: string;
}
